// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACnyN4EIR9GeOgT3lUBw7LgsEZYrMuGNc',
    appId: '1:788585311629:web:36a697b373e96233a761c4',
    messagingSenderId: '788585311629',
    projectId: 'quiz-bfcf9',
    authDomain: 'quiz-bfcf9.firebaseapp.com',
    storageBucket: 'quiz-bfcf9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpsHAl9MpD6nFCDt-wKRsV0oxXu5x7Nvk',
    appId: '1:788585311629:android:838a6149a13192f7a761c4',
    messagingSenderId: '788585311629',
    projectId: 'quiz-bfcf9',
    storageBucket: 'quiz-bfcf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT3tITnKeUqOXdXXwvYRYb3gEWcvG2-xQ',
    appId: '1:788585311629:ios:474c61c107e1a6e3a761c4',
    messagingSenderId: '788585311629',
    projectId: 'quiz-bfcf9',
    storageBucket: 'quiz-bfcf9.appspot.com',
    iosClientId: '788585311629-7ghh36eggp79qevaruieqrktdbksplae.apps.googleusercontent.com',
    iosBundleId: 'com.example.howlkar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT3tITnKeUqOXdXXwvYRYb3gEWcvG2-xQ',
    appId: '1:788585311629:ios:474c61c107e1a6e3a761c4',
    messagingSenderId: '788585311629',
    projectId: 'quiz-bfcf9',
    storageBucket: 'quiz-bfcf9.appspot.com',
    iosClientId: '788585311629-7ghh36eggp79qevaruieqrktdbksplae.apps.googleusercontent.com',
    iosBundleId: 'com.example.howlkar',
  );
}
